from abc import ABCMeta, abstractmethod
from typing import Iterable


class VKApi(metaclass=ABCMeta):
    user_id: int
    token: str

    @abstractmethod
    def __init__(self, user_id: int): ...
    @abstractmethod
    async def get_conversation(self, conversation_id: int) -> object: ...
    @abstractmethod
    async def get_message(self, conversation_id: int, message_ids: int | Iterable[int]) -> list: ...
    @abstractmethod
    async def read_message(self, conversation_id: int, message_ids: int | Iterable[int]) -> list: ...
    @abstractmethod
    async def get_group(self, group_id: int) -> ...: ...
    @abstractmethod
    async def get_user(self, group_id: int) -> ...: ...
    @abstractmethod
    async def get_chat(self, group_id: int) -> ...: ...
